Algoritmo "calculo imc"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2023
Var
m,a,imc: real


Inicio
 escreva ("massa (kg):")
 leia (m)
 escreva("altura (m):")
 leia(a)
 imc<- m(a^2)
 escreval("imc:",imc:5:2)
 se(imc >= 18.5) e (imc < 25)entao
 
 escreva("parabens voçe esta no seu peso ideal ")
 senao
  escreva("vc nao esta no seu peso ideal")
 fimse

Fimalgoritmo