Algoritmo "porcento"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis 
      imposto,preco: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva("qual valor do produto")
       leia(preco)
       imposto<- (preco*60)/100
       escreva("imposto sera de:",imposto)

Fimalgoritmo