Algoritmo "temperatura"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis 
        f,c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva("qual a temperatura aqui")
       leia (f)
       c<-(f-32)/1.8
       escreva ("no brasil esta fazendo",c)

Fimalgoritmo